import type { Privilege } from "@/types/content";

/*
  AUTO-GENERATED from legacy/imtiyozlar.html by scripts/extract-privileges.mjs.

  This is statutory legal content. Do not reword, reformat, summarise, or
  machine-translate any field — `legalBasis` in particular cites binding Uzbek
  legal acts and must stay verbatim. Corrections should come from the source
  legislation, not from editing prose here.
*/

export const privileges: Privilege[] = [
  {
    id: 1,
    category: "talim",
    tag: "Ta'lim muassasalari",
    title: "Xususiy o'quv markazlariga sinf xonalaridan bepul foydalanish",
    description: "2024-yilda kamida 1000 ta umumta'lim muassasasining bo'sh sinf xonalari xususiy o'quv markazlariga kasb-hunar va xorijiy tillarni o'qitish faoliyatini yo'lga qo'yish uchun bepul foydalanishga beriladi.",
    subject: "Xususiy o'quv markazlari",
    duration: "Doimiy",
    legalBasis: "PQ-239, 27.06.2024-y. (4-band)",
  },
  {
    id: 2,
    category: "it",
    tag: "IT va innovatsiya",
    title: "IT-park va raqamli texnologiyalar tashkilotlariga bepul bino",
    description: "IT-parkning tavsiyanomasiga asosan bo'sh turgan davlat ko'chmas mulk obyektlari, Raqamli texnologiyalar vazirligi tizimidagi tashkilotlar hamda IT-park filiallarining bo'sh binolari va maydonlari bir yilgacha muddatga bepul foydalanish huquqi asosida beriladi.",
    subject: "IT-xizmatlar eksportini kengaytirish dasturi ishtirokchilari",
    duration: "1 yilgacha muddatga",
    legalBasis: "PQ-87, 26.02.2024-y. (2-band)",
  },
  {
    id: 3,
    category: "it",
    tag: "IT va innovatsiya",
    title: "Dastur muddati tugagach to'g'ridan-to'g'ri ijara shartnomasi",
    description: "Dasturda ishtirok etuvchi korxonalarga bir yillik bepul foydalanish shartnomasi muddati tugagach, ular egallab turgan bino va maydonlar bo'yicha «E-auksion» elektron savdo platformasida shakllangan hududiy o'rtacha ijara haqi miqdorida to'g'ridan-to'g'ri shartnoma tuziladi.",
    subject: "Dastur ishtirokchisi korxonalar",
    duration: "Doimiy",
    legalBasis: "Tegishli hukumat qarorlari asosida",
  },
  {
    id: 4,
    category: "it",
    tag: "IT va innovatsiya",
    title: "Malaka oshirish uchun eng kam stavkada ijara",
    description: "Hududlarda bo'sh turgan va bir yildan buyon auksion savdolarida sotilmagan davlat mulki bino-inshootlari, shuningdek kasb-hunar kollejlarining bo'sh binolari dastur ishtirokchilariga xodimlarni o'qitish, malakasini oshirish va «amaliy monomarkaz» tashkil etish uchun tanlov (yagona talabgor bo'lganda — to'g'ridan-to'g'ri shartnoma) asosida eng kam ijara stavkasida beriladi.",
    subject: "«20 ming tadbirkor — 500 ming malakali mutaxassis» dasturi ishtirokchilari",
    duration: "Doimiy",
    legalBasis: "PF-93, 12.06.2023-y. (7-band, 12-xatboshi)",
  },
  {
    id: 5,
    category: "boshqa",
    tag: "Hunarmandchilik va meros",
    title: "Hunarmandlarga madaniy meros obyektlari 50% chegirma bilan",
    description: "Madaniy meros obyektlarini hunarmandlarga ijaraga berishda auksionga chiqariladigan boshlang'ich narx amaldagi stavkaga nisbatan 50 foiz miqdorida belgilanadi.",
    subject: "Hunarmandlar",
    duration: "Doimiy",
    legalBasis: "PF-91, 12.06.2023-y. (10-band, 4-xatboshi)",
  },
  {
    id: 6,
    category: "boshqa",
    tag: "Sport",
    title: "Xususiy shaxmat klublariga bepul joy",
    description: "Xususiy shaxmat klublariga shaxmat to'garaklarini tashkil etish va aholiga xizmat ko'rsatish uchun davlat mulki obyektlari va hududlardagi «Yoshlar markazlari»dan ijara to'lovisiz (kommunal to'lovlar bundan mustasno) joy ajratiladi.",
    subject: "Xususiy shaxmat klublari",
    duration: "2024-yil 1-yanvardan boshlab",
    legalBasis: "PQ-150, 08.05.2023-y. (10-band)",
  },
  {
    id: 7,
    category: "boshqa",
    tag: "Hududiy dasturlar",
    title: "Kasanachilarni jalb qilganlar uchun 50% chegirma",
    description: "Kasanachilarni jalb qilgan tadbirkorlik subyektlariga davlat mulki obyektlari ijara to'lovlarini 50 foizga kamaytirgan holda ijaraga beriladi.",
    subject: "Kasanachilarni jalb qilgan tadbirkorlik subyektlari",
    duration: "Doimiy",
    legalBasis: "PQ-70, 23.02.2023-y. (2-ilova)",
  },
  {
    id: 8,
    category: "boshqa",
    tag: "Hududiy dasturlar",
    title: "Hudud toifasiga qarab boshlang'ich narxni 50% pasaytirish",
    description: "Tadbirkorlik faoliyatini tuman va shaharlarning toifalaridan kelib chiqib qo'llab-quvvatlash choralariga muvofiq, tadbirkorlik subyektlariga davlat mulki obyektlarini ijaraga berishda auksionga chiqariladigan boshlang'ich narx amaldagi stavkaga nisbatan 50 foizga tushiriladi.",
    subject: "Barcha tadbirkorlik subyektlari",
    duration: "Doimiy",
    legalBasis: "PQ-287, 30.12.2022-y. (4-band, 2-xatboshi)",
  },
  {
    id: 9,
    category: "ijtimoiy",
    tag: "Ijtimoiy himoya",
    title: "«Ayollar daftari»dagi xotin-qizlarni ishga qabul qilganda chegirma",
    description: "«Ayollar daftari»ga kiritilgan ishsiz xotin-qizlarni ishga qabul qilganda, umumiy ijara maydoniga nisbatan ijara to'lovlaridan 50 foiz miqdorida imtiyoz beriladi.",
    subject: "Barcha tadbirkorlik subyektlari",
    duration: "Doimiy",
    legalBasis: "Tegishli hukumat qarorlari asosida",
  },
  {
    id: 10,
    category: "ijtimoiy",
    tag: "Ijtimoiy himoya",
    title: "Xotin-qizlar ustunlik qiladigan korxonalar uchun 5 yillik ozodlik",
    description: "Ishlab chiqarish sohasida faoliyat yurituvchi va xodimlar umumiy sonining kamida 70 foizi «Ayollar daftari»ga kiritilgan xotin-qizlar bo'lgan tadbirkorlik subyektlari davlat mulki obyektlari uchun ijara haqi to'lovidan 5 yilga ozod etiladi.",
    subject: "Ishlab chiqarish bilan shug'ullanuvchi tadbirkorlik subyektlari",
    duration: "5 yilgacha",
    legalBasis: "Tegishli hukumat qarorlari asosida",
  },
  {
    id: 12,
    category: "ijtimoiy",
    tag: "Ijtimoiy himoya",
    title: "Qishloqlarda ayollar bandligi uchun 90% imtiyoz",
    description: "Mehnat resurslari zich bo'lgan qishloq hududlari reyestriga kiritilgan joylarda xotin-qizlar bandligini ta'minlagan tadbirkorlik subyektlari davlat mulki obyektlarini ijaraga olishda ijara to'lovlaridan 90 foiz miqdorida imtiyozdan foydalanadi (elektron savdolarsiz, alohida shartlar asosida).",
    subject: "Kamida 10 xodimli, ularning kamida 50%i xotin-qizlar bo'lgan kichik tadbirkorlik subyektlari",
    duration: "2022-yil sentabrdan 2025-yil yanvargacha",
    legalBasis: "PF-87, 07.03.2022-y. (9-band, 3-ilova)",
  },
  {
    id: 13,
    category: "boshqa",
    tag: "Sport",
    title: "Mahallada sport to'garaklari uchun 50% eng kam stavka",
    description: "Sport to'garaklarini tashkil etish uchun mahallada bo'sh turgan davlat mulki bino va inshootlari elektron savdolarsiz, belgilangan eng kam ijara to'lovi stavkasining 50 foizi miqdorida ijaraga beriladi.",
    subject: "Barcha tadbirkorlik subyektlari",
    duration: "Doimiy",
    legalBasis: "PQ-92, 19.01.2022-y. (1-ilova, 9-band)",
  },
  {
    id: 14,
    category: "boshqa",
    tag: "Sport",
    title: "Sportchi-murabbiylarga to'garak tashkil etish uchun imtiyoz",
    description: "Olimpiya va Paralimpiya hamda Osiyo va Paraosiyo o'yinlari, jahon, Osiyo va respublika chempionatlarida so'nggi 5 yilda g'olib va sovrindor (1–3 o'rin) bo'lgan sportchi-murabbiylarga, shuningdek olis va chekka hududlarda faoliyat yurituvchi sportchi-murabbiylarga to'garak tashkil etish uchun tuman va shaharlarda bo'sh turgan davlat mulki bino va inshootlari elektron savdolarsiz, eng kam stavkaning 50 foizi miqdorida ijaraga beriladi.",
    subject: "Ko'rsatilgan yutuqlarga ega sportchi-murabbiylar",
    duration: "Doimiy",
    legalBasis: "PF-6260, 13.07.2021-y. (13-band); PQ-376, 21.09.2022-y. (1-ilova)",
  },
  {
    id: 15,
    category: "ijtimoiy",
    tag: "Ijtimoiy himoya",
    title: "«Yoshlar daftari»dagi yoshlarni ishga qabul qilganda chegirma",
    description: "«Yoshlar daftari»ga kiritilgan ishsiz yoshlarni ishga qabul qilganda, umumiy ijara maydoniga nisbatan ijara to'lovlaridan 50 foiz miqdorda imtiyoz beriladi.",
    subject: "Barcha tadbirkorlik subyektlari",
    duration: "Doimiy",
    legalBasis: "Tegishli hukumat qarorlari asosida",
  },
  {
    id: 16,
    category: "ijtimoiy",
    tag: "Ijtimoiy himoya",
    title: "Yoshlar ustunlik qiladigan korxonalar uchun 5 yillik ozodlik",
    description: "Ishlab chiqarish sohasida faoliyat yurituvchi va xodimlar umumiy sonining kamida 70 foizi «Yoshlar daftari»ga kiritilgan yoshlar bo'lgan tadbirkorlik subyektlari davlat mulki obyektlari uchun ijara haqi to'lovidan 5 yilga ozod etiladi.",
    subject: "Ishlab chiqarish bilan shug'ullanuvchi tadbirkorlik subyektlari",
    duration: "5 yilgacha",
    legalBasis: "Tegishli hukumat qarorlari asosida",
  },
  {
    id: 17,
    category: "talim",
    tag: "Ta'lim muassasalari",
    title: "Bog'cha oshxonasidan bepul foydalanish (autsorsing)",
    description: "Davlat maktabgacha ta'lim tashkilotida ovqatlantirish autsorsing usulida tashkil etilganda, ijara shartnomasi doirasida autsorserga vaqtincha foydalanishga beriladigan oshxonaning ishlab chiqarish xonalari, asbob-uskunalari, idish-tovoqlari va mebelidan foydalanganlik uchun bepul foydalanish huquqi belgilanadi.",
    subject: "Autsorsing usulida tashkil etilgan tadbirkorlik subyektlari",
    duration: "Doimiy",
    legalBasis: "VM-626, 25.07.2019-y. (5-band, 3-xatboshi)",
  },
  {
    id: 18,
    category: "ijtimoiy",
    tag: "Ijtimoiy himoya",
    title: "Nogironligi bo'lgan shaxslar uchun 50% chegirma",
    description: "Davlat mulkini ijaraga olgan alohida toifadagi (nogironligi mavjud yoki xodimlarining ko'proq qismi nogironlarni tashkil etuvchi) tadbirkorlik subyektlariga ijara to'lovi ushbu obyektga nisbatan auksion savdolari natijalari bo'yicha belgilangan ijara to'lovining 50 foizi miqdorida belgilanadi.",
    subject: "Nogironligi bo'lgan yoki nogironlarni ishga qabul qilgan tadbirkorlik subyektlari",
    duration: "Doimiy",
    legalBasis: "PQ-3782, 11.06.2018-y. (1-band)",
  },
  {
    id: 19,
    category: "ijtimoiy",
    tag: "Ijtimoiy himoya",
    title: "Yosh tadbirkorlarga ishlab chiqarish maydonlaridan bepul foydalanish",
    description: "O'zbekiston yoshlar ittifoqi a'zosi bo'lgan yosh tadbirkorlarga «Yoshlar ishlab chiqarish klasterlari» hududida joylashgan ishlab chiqarish maydonlari korxona tashkil topguniga qadar, ammo 5 yildan ko'p bo'lmagan muddatga bepul foydalanish huquqi asosida beriladi.",
    subject: "O'zbekiston yoshlar ittifoqi a'zosi bo'lgan yosh tadbirkorlar",
    duration: "5 yilgacha",
    legalBasis: "VM-834, 16.10.2017-y. (5-band)",
  },
  {
    id: 20,
    category: "ijtimoiy",
    tag: "Ijtimoiy himoya",
    title: "Yoshlar ittifoqi so'roviga ko'ra bo'sh mulkdan bepul foydalanish",
    description: "O'zbekiston yoshlar ittifoqi a'zosi bo'lgan yosh tadbirkorlarga foydalanilmayotgan, shu jumladan erkin iqtisodiy va kichik sanoat zonalari hududida joylashgan davlat mulki, Yoshlar ittifoqining shahar va tuman kengashlari iltimosiga ko'ra 5 yildan ko'p bo'lmagan muddatga bepul foydalanish huquqi asosida beriladi.",
    subject: "O'zbekiston yoshlar ittifoqi a'zosi bo'lgan yosh tadbirkorlar",
    duration: "5 yilgacha",
    legalBasis: "PF-6208, 20.05.2021-y. (1-band)",
  },
  {
    id: 21,
    category: "boshqa",
    tag: "Hududiy dasturlar",
    title: "Navoiy viloyati chekka tumanlarida 10 yilgacha bepul foydalanish",
    description: "Navoiy viloyatining Tomdi, Uchquduq, Konimex, Nurota tumanlari va Zarafshon shahrida joylashgan foydalanilmay bo'sh yotgan davlat obyektlari, yangi ish o'rinlari yaratish sharti bilan, ushbu obyektlar negizida tadbirkorlik faoliyatini yo'lga qo'yish istagini bildirgan tadbirkorlik subyektlariga o'n yil muddatgacha bepul foydalanish huquqi asosida beriladi.",
    subject: "Barcha tadbirkorlik subyektlari",
    duration: "10 yilgacha",
    legalBasis: "PQ-3301, 29.09.2017-y. (9-band)",
  },
  {
    id: 23,
    category: "boshqa",
    tag: "Hunarmandchilik va meros",
    title: "Madaniy meros obyektlariga investitsiya evaziga 80% ozodlik",
    description: "Moddiy madaniy meros obyektlarini investitsiya kiritish sharti bilan ijaraga olgan tadbirkorlik subyektlari, shartnoma tuzilgan kundan boshlab besh yil muddatga ijara to'lovining hisoblab chiqilgan qiymatining 80 foizi miqdorida ijara to'lovini to'lashdan ozod etiladi.",
    subject: "Madaniy meros obyektlarini investitsiya sharti bilan olgan tadbirkorlik subyektlari",
    duration: "Doimiy",
    legalBasis: "VM-53, 06.03.2014-y. (1-ilova, 32-band)",
  },
  {
    id: 24,
    category: "talim",
    tag: "Ta'lim muassasalari",
    title: "Tugatilayotgan bog'chalar binosini nodavlat bog'chalarga ijaraga berish",
    description: "Tugatilayotgan davlat maktabgacha ta'lim tashkilotlarining bo'shayotgan binolari va inshootlari, mavjud jihozlari va asbob-uskunalari bilan birgalikda, keyinchalik sotib olish huquqi bilan 3 yilgacha muddatga ijara haqi undirmasdan nodavlat maktabgacha ta'lim tashkilotlariga ijaraga beriladi.",
    subject: "Barcha tadbirkorlik subyektlari",
    duration: "3 yilgacha",
    legalBasis: "VM-313, 24.06.1999-y. (2-band)",
  },
];
